### ISSUE TITLE
[Bug] appendonlyam_handler.c:1790:25: error: ‘segfile_count’ may be used uninitialized

### ISSUE THREAD

**Issue by avamingli** [apache/cloudberry#989]
### Apache Cloudberry version

main branch commit: 644b4e307380954e986f048d0a7910a3063e524e

### What happened

```shell
appendonlyam_handler.c: In function ‘appendonly_index_build_range_scan’:
appendonlyam_handler.c:1790:25: error: ‘segfile_count’ may be used uninitialized [-Werror=maybe-uninitialized]
 1790 |                         FreeAllSegFileInfo(seginfo, segfile_count);
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
aocsam_handler.c: In function ‘aoco_index_build_range_scan’:
aocsam_handler.c:1952:25: error: ‘segfile_count’ may be used uninitialized [-Werror=maybe-uninitialized]
 1952 |                         FreeAllAOCSSegFileInfo(seginfo, segfile_count);
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors

```

### How to reproduce

config, make

### Operating System

Ubuntu

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/cloudberry/blob/main/CODE_OF_CONDUCT.md).

**Comment by avamingli** [comment]
make failed, and something bad may be behind the segfile_count is not assigned any more.
git blame show that it's introduced by https://github.com/apache/cloudberry/pull/897

@reshke @yjhjstz

**Comment by jiaqizho** [comment]
Also `if (!FIPS_mode_set)`(in contrib/pgcrypto/openssl.c) will got an `WError`..

**Comment by yjhjstz** [comment]
merge https://github.com/apache/cloudberry/pull/986 asap.

**Comment by reshke** [comment]
Maybe we should configure CI with more strict compiler flags...
LGTM #986

**Comment by yjhjstz** [comment]
```c++
/*
	 * When Parallel index build,there is no additional operation to update the number of tuples
	 * that supports this logic. Uniform processing is used here. 
	 */ 
	if (progress)
	{
		seginfo = GetAllFileSegInfo(heapRelation, snapshot, &segfile_count, NULL);
		for (int seginfo_no = 0; seginfo_no < segfile_count; seginfo_no++)
		{
			total_blockcount += seginfo[seginfo_no]->varblockcount;
		}
		pgstat_progress_update_param(PROGRESS_SCAN_BLOCKS_TOTAL, total_blockcount);
	}
```
@reshke  this need to check, I will merge quick fix https://github.com/apache/cloudberry/pull/986. 
issue keep open here.

**Comment by avamingli** [comment]
>  and something bad may be behind the failure, because segfile_count is not assigned any more. It's assigned before as:
> 
> ```
> 	/*
> 	 * When Parallel index build,there is no additional operation to update the number of tuples
> 	 * that supports this logic. Uniform processing is used here. 
> 	 */ 
> 	if (progress)
> 	{
> 		seginfo = GetAllFileSegInfo(heapRelation, snapshot, &segfile_count, NULL);
> 		for (int seginfo_no = 0; seginfo_no < segfile_count; seginfo_no++)
> 		{
> 			total_blockcount += seginfo[seginfo_no]->varblockcount;
> 		}
> 		pgstat_progress_update_param(PROGRESS_SCAN_BLOCKS_TOTAL, total_blockcount);
> 	}
> ```
> 
> git blame show that it's changed by [#897](https://github.com/apache/cloudberry/pull/897)
> 
> [@reshke](https://github.com/reshke) [@yjhjstz](https://github.com/yjhjstz) [@x4m](https://github.com/x4m) [@my-ship-it](https://github.com/my-ship-it) [@leborchuk](https://github.com/leborchuk)

Could someone please review this?

**Comment by reshke** [comment]
Upstream does this different way:
https://github.com/greenplum-db/gpdb-archive/blob/main/src/backend/access/aocs/aocsam_handler.c#L2335
looks like we need to cherry-pick block directory support and restore this logic
https://github.com/greenplum-db/gpdb-archive/blob/main/src/backend/access/aocs/aocsam_handler.c#L2196
i will take another look soon
