### ISSUE TITLE
[Bug] ic-good-opt, ic-good-opt-on and ic-cbdb-parallel tests failed on Rocky 8

### ISSUE THREAD

**Issue by tuhaihe** [apache/cloudberry#1538]
### Apache Cloudberry version

main

### What happened

There are 3 tests that failed when running on Rocky 8 dev container:

- ic-good-opt
- ic-good-opt-on
- ic-cbdb-parallel

## ic-good-opt

```
Found regression.diffs at: ./src/test/regress/regression.diffs
diff -I HINT: -I CONTEXT: -I GP_IGNORE: -U3 /__w/cloudberry/cloudberry/src/test/regress/expected/motion_socket.out /__w/cloudberry/cloudberry/src/test/regress/results/motion_socket.out
--- /__w/cloudberry/cloudberry/src/test/regress/expected/motion_socket.out	2026-01-19 20:42:27.563870372 -0800
+++ /__w/cloudberry/cloudberry/src/test/regress/results/motion_socket.out	2026-01-19 20:42:27.566870369 -0800
@@ -69,8 +69,9 @@
 
 $$ LANGUAGE plpython3u;
 SELECT check_motion_sockets();
- check_motion_sockets 
-----------------------
- 
-(1 row)
-
+ERROR:  TypeError: __init__() got an unexpected keyword argument 'capture_output'
+CONTEXT:  Traceback (most recent call last):
+  PL/Python function "check_motion_sockets", line 40, in <module>
+    capture_output=True, check=True).stdout
+  PL/Python function "check_motion_sockets", line 422, in run
+PL/Python function "check_motion_sockets"
```

## ic-good-opt-on

```
Found regression.diffs at: ./src/test/regress/regression.diffs
diff -I HINT: -I CONTEXT: -I GP_IGNORE: -U3 /__w/cloudberry/cloudberry/src/test/regress/expected/motion_socket.out /__w/cloudberry/cloudberry/src/test/regress/results/motion_socket.out
--- /__w/cloudberry/cloudberry/src/test/regress/expected/motion_socket.out	2026-01-19 20:46:44.227418740 -0800
+++ /__w/cloudberry/cloudberry/src/test/regress/results/motion_socket.out	2026-01-19 20:46:44.230418730 -0800
@@ -69,8 +69,9 @@
 
 $$ LANGUAGE plpython3u;
 SELECT check_motion_sockets();
- check_motion_sockets 
-----------------------
- 
-(1 row)
-
+ERROR:  TypeError: __init__() got an unexpected keyword argument 'capture_output'
+CONTEXT:  Traceback (most recent call last):
+  PL/Python function "check_motion_sockets", line 40, in <module>
+    capture_output=True, check=True).stdout
+  PL/Python function "check_motion_sockets", line 422, in run
+PL/Python function "check_motion_sockets"
```

## ic-cbdb-parallel

```
Found regression.diffs at: ./src/test/regress/regression.diffs
diff -I HINT: -I CONTEXT: -I GP_IGNORE: -U3 /__w/cloudberry/cloudberry/src/test/regress/expected/motion_socket.out /__w/cloudberry/cloudberry/src/test/regress/results/motion_socket.out
--- /__w/cloudberry/cloudberry/src/test/regress/expected/motion_socket.out	2026-01-19 20:44:50.410975936 -0800
+++ /__w/cloudberry/cloudberry/src/test/regress/results/motion_socket.out	2026-01-19 20:44:50.412975934 -0800
@@ -69,8 +69,9 @@
 
 $$ LANGUAGE plpython3u;
 SELECT check_motion_sockets();
- check_motion_sockets 
-----------------------
- 
-(1 row)
-
+ERROR:  TypeError: __init__() got an unexpected keyword argument 'capture_output'
+CONTEXT:  Traceback (most recent call last):
+  PL/Python function "check_motion_sockets", line 40, in <module>
+    capture_output=True, check=True).stdout
+  PL/Python function "check_motion_sockets", line 422, in run
+PL/Python function "check_motion_sockets"
```

### How to reproduce

You can see the test here: https://github.com/apache/cloudberry/actions/runs/21159078720/job/60850595340?pr=1518

### Operating System

Rocky 8.10

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/cloudberry/blob/main/CODE_OF_CONDUCT.md).

**Comment by lss602726449** [comment]
Which python version you use now. **capture_output** is only work in **python 3.7+** @tuhaihe

**Comment by tuhaihe** [comment]
> Which python version you use now. **capture_output** is only work in **python 3.7+** [@tuhaihe](https://github.com/tuhaihe)

should be the default Python version - 3.6.8 on Rocky Linux 8. Now I created one commit https://github.com/apache/cloudberry/pull/1518/commits/e3db1c0ac7e342e33842c1691476d04a07c5d162 trying to fix it in PR #1518. Welcome to review it.

**Comment by tuhaihe** [comment]
Has been fixed via #1518.
